config/routes.rb
Aa::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :news_items

  get 'about_us' => "welcome#about_us"
  get 'impressum' => "welcome#imprint"
  get 'privacy' => "welcome#privacy"
  get 'terms' => "welcome#terms"
  get 'philosophy' => "welcome#philosophy"
  get 'quality' => "welcome#quality"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         
  has_paper_trail
  
  def admin_permalink
      admin_admin_user_path(self)
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
   belongs_to :product
   validates_presence_of :article_number
   validates_uniqueness_of :article_number
   
   has_paper_trail
   
   def admin_permalink
       admin_article_path(self)
   end
   
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  mount_uploader :category_icon, CategoryIconUploader
  has_many :systems, dependent: :destroy
  
  has_paper_trail
  
  def admin_permalink
      admin_category_path(self)
  end
  
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  
  def self.current_news(amount = 2)
      find(:all, :limit => amount, :order => "publication_date DESC")
  end
  
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  belongs_to :system
  has_many :articles, dependent: :destroy
  
  validates_presence_of :name
  validates_presence_of :system
  
  mount_uploader :ldt, LdtUploader
  mount_uploader :ldtzip, LdtzipUploader
  
  has_paper_trail
  
  def admin_permalink
      admin_product_path(self)
  end
  
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  
  mount_uploader :image, NewsItemImageUploader
  
end

app/models/system.rb
class System < ActiveRecord::Base
  
  has_many :products, dependent: :destroy
  belongs_to :category
  validates_presence_of :name
  validates_presence_of :category
  
  has_paper_trail
  
  def admin_permalink
      admin_system_path(self)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
  
  def user_for_paper_trail
      admin_user_signed_in? ? current_admin_user.email : 'Unbekannter Nutzer'
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @news_items = NewsItem.current_news
    @slides = Slide.find(:all, :order => "position ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def default_content_for(name, &block)
    name = name.kind_of?(Symbol) ? ":#{name}" : name
    out = eval("yield #{name}", block.binding)
    concat(out || capture(&block))
  end
  
  
end

app/views/admin/articles/index.xml.erb
<?xml version="1.0" ?> 
<systemdata>
	<system>
		<systemname><%= @articles.first.product.system.name %></systemname>
		<productname><%= @articles.first.product.name %></productname>
		<image href="file://nothing/here/"></image>
		<articles>
			<% @articles.each do | article | %>
			<article>
				<product><%= article.product.name %></product>
				<% article.attributes.each_pair do |name, value| %>
					<<%= name %>><%= value %></<%= name %>>
				<% end %>
			</article>
			<% end %>
		</articles>
	</system>
</systemdata>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
    = csrf_meta_tag
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application" 
    = javascript_include_tag "http://code.jquery.com/jquery-migrate-1.2.1.js"
    = yield :head
    %title
      -default_content_for :title do
        BPS Leuchten
  %body.bp
    #outer
      #wrapper
        #main
          #language-switch
            %ul
              %li
                = link_to("de", "#")
              %li
                = link_to("en", "#")
              / %li{:class => "last"}
              /   = link_to("ru", i18n_link(request.path, "ru"))
          #navigation
            %ul
              %li
                = link_to t("navigation.home"), root_path
              %li
                = link_to t("navigation.news"), news_items_path
              %li
                = link_to t("navigation.about-us"), about_us_path
              %li
                = link_to t("navigation.products"), "#"
              %li
                = link_to t("navigation.references"), "#"
              %li
                = link_to t("navigation.search"), "#"
              %li
                = link_to t("navigation.service"), "#"
            .clearer
        
          #content
            = yield
            .clearer
            #bottom-navigation
              %ul
                %li#imprint
                  = link_to t("navigation.imprint"), "/impressum"
                %li#term
                  =link_to t("navigation.terms"), "/terms"
                %li#privacy
                  =link_to t("navigation.privacy"), "/privacy"  
              .clearer
        #sidebar
          = yield(:sidebar)

app/views/welcome/index.html.haml
#willkommen{:class => 'hello'}
  - unless @slides.empty?
    - @slides.each_with_index do |slide,index|
      = image_tag(slide.image.url, :size => "700x400", :class => index == 0 ? "first" : "")
  - else
    - (1..11).each do |i|
      = image_tag( "/slideshow/slide%02i.jpg" % i, :size => "700x400", :class => i == 0 ? "first" : "")
-content_for :sidebar do
  #news
    .news-wrapper
      %h2
        = t('home.news')
      - @news_items.each do |news_item|
        .news-item
          %h3
            = h news_item.title
          %p
            = news_item.teaser.html_safe
          - if news_item.system_id.blank?
            = link_to "#{t "more"}&nbsp;&gt;&gt;".html_safe, news_items_path(:anchor => "news-item-#{news_item.id}")
          - else
            = link_to "#{t "more"}&nbsp;&gt;&gt;".html_safe, landingpage_system_path(news_item.system_id)
  